FROM ubuntu:16.04

LABEL maintainer="Sara <howtoanalyse.github.io/>"

# Pick up some TF dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
        curl \
        libfreetype6-dev \
        libhdf5-serial-dev \
        libpng12-dev \
        libzmq3-dev \
        pkg-config \
        python3 \
        python3-dev \
        rsync \
        software-properties-common \
        unzip \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN curl -O https://bootstrap.pypa.io/get-pip.py && \
    python3 get-pip.py && \
    rm get-pip.py

RUN pip3 --no-cache-dir install \
        Pillow \
        h5py \
        ipykernel \
        jupyter \
        matplotlib \
        numpy \
        pandas \
        scipy \
        sklearn \
        tensorflow \
        && \
    python3 -m ipykernel.kernelspec

RUN ln -s -f /usr/bin/python3 /usr/bin/python
ADD test.py /

# TensorBoard
EXPOSE 6006
# IPython
EXPOSE 8888

CMD ["python"]